hyperskill_project:
  id: 64
  ide_files: https://stepik.org/media/attachments/lesson/210127/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 343
  step: 5485
  is_completed: false
- id: 344
  step: 5486
  is_completed: false
- id: 345
  step: 5487
  is_completed: false
- id: 346
  step: 5488
  is_completed: false
- id: 347
  step: 5489
  is_completed: false
